#pragma once

#ifndef AI_CONFIG_H_INC
#define AI_CONFIG_H_INC

// Lets compile_flags.txt parse Assimp before CMake generates config.h. Keep these defaults
// and the keys used by mesh_assimp.cpp in sync with the CMake build.
#define AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON_DEFAULT 10e-3f
#define AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE "PP_GSN_MAX_SMOOTHING_ANGLE"
#define AI_CONFIG_IMPORT_NO_SKELETON_MESHES "IMPORT_NO_SKELETON_MESHES"
#define AI_CONFIG_IMPORT_MD5_NO_ANIM_AUTOLOAD "IMPORT_MD5_NO_ANIM_AUTOLOAD"
#define AI_CONFIG_IMPORT_MDL_COLORMAP "IMPORT_MDL_COLORMAP"
#define AI_CONFIG_IMPORT_UNREAL_HANDLE_FLAGS "UNREAL_HANDLE_FLAGS"
#define AI_CONFIG_IMPORT_ASE_RECONSTRUCT_NORMALS "IMPORT_ASE_RECONSTRUCT_NORMALS"

#endif
